Rails 5.2
Was being blocked by simpleform; moved that to ~>4 and then ran `bundle update` successfully.

`rails app:update` modified and generated a bunch of config files.

Manually add bootsnap gem (required in `config/boot.rb`)

Manually add `listen` gem (server failing to boot - `config/environments/development.rb` `config.file_watcher` requires it: https://stackoverflow.com/questions/38663706/loaderror-could-not-load-the-listen-gem-rails-5)

Manually create Sprockets manifest.js (updated gem). Fix admin.css.scss and application.css.scss imports (rename file; failing due to not finding). Then getting a Sprockets error: ActionView::Template::Error (undefined method `start_with?' for /\.(?:svg|eot|woff|woff2|ttf)\z/:Regexp):. Added to Gemfile and locked sprockets to 3.7.2.